my:
  prod:
    id: 10
    name: narendar
    cost: 25000
    mo:
      mid: 25
      p:
        p1: nalla
        p2: narendar
        p3: reddy
    versions:
    - a1
    - a2
    - a3
    mods:
        m1: ${my.prod.id}    #this is called placeholder. used to re-use  
        m2: ${my.prod.mo.mid} # existed key value.
     
      